---
- name: upgrade
  action: apt update_cache=yes

- name: Install app dependencies
  action: 'apt pkg={{ item }}'
  with_items:
    - 'build-essential'
    - 'curl'
    - 'libssl-dev'
    - 'libyaml-dev'
    - 'libreadline6-dev'
    - 'zlib1g-dev'
    - 'libcurl4-openssl-dev'
    - 'git'
    - 'nginx'
    - 'imagemagick'
    - 'libmagickwand-dev'
    - 'nodejs'
    - 'htop'
    - 'nodejs'
    - 'python-psycopg2'
    - 'postfix'

- name: Create deployment directory for application
  file: path={{ deploy_dir }} owner={{user}} group={{user}} state=directory

- name: Remove the config symlink, if exists
  command: rm -rf {{ deploy_dir }}/shared/config

- name: Create shared directory for  application
  file: path={{ deploy_dir }}/shared owner={{user}} group={{user}} state=directory

- name: Create config directory for application
  file: path={{ deploy_dir }}/shared/config owner={{user}} group={{user}} state=directory

- name: copy database.yml to config directory for application
  action: template src=database.yml dest={{ deploy_dir }}/shared/config mode=0700 owner={{user}} group={{user}}