development:
  sessions:
    default:
      database: fitohoney_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: fitohoney_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false
production:
  sessions:
    default:
      database: fitohoney_production
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false
    