user: 'deploy'
home: '/home/{{ user }}'
name: 'fitohoney'
deploy_dir: '{{ home }}/www/{{ name }}'
database_name: fitohoney
database_username: deploy
database_password: qwerty

#ruby
#ruby_version: '2.1.5'
#rbenv_root: '{{ home }}/.rbenv'
rvm1_rubies:
  - 'ruby-2.2.1'
rvm1_delete_ruby:
rvm1_install_path: '/usr/local/rvm'
rvm1_install_flags: '--auto-dotfiles'
rvm1_ruby_install_flags:
rvm1_user: 
  - '{{user}}'
rvm1_rvm_latest_installer: 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer'
rvm1_rvm_version: 'stable'
rvm1_rvm_check_for_updates: True
rvm1_gpg_keys: 'D39DC0E3'
rvm1_gpg_key_server: 'hkp://keys.gnupg.net'
rvm1_autolib_mode: 3
rvm1_temp_download_path: '/tmp'
rvm1_default_ruby_version: '{{ rvm1_rubies | last if rvm1_rubies and rvm1_rubies is iterable else "" }}'
rvm1_rvm: '{{ rvm1_install_path }}/bin/rvm'
rvm1_symlink_binaries:
  - 'bundle'
  - 'bundler'
  - 'erb'
  - 'executable-hooks-uninstaller'
  - 'gem'
  - 'irb'
  - 'rake'
  - 'rdoc'
  - 'ri'
  - 'ruby'
  - 'testrb'
rvm1_symlink_to: '/usr/local/bin'